### ISSUE TITLE
Tracking issue for v0.3 

### ISSUE THREAD

**Issue by ev-br** [ev-br/mc_lib#31]
Jotting down things TODO after merging gh-28 or gh-30:

- [x] Check pip pending deprecation: `DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.`
- [x] what's the failure mode of `pip install -e .`
- [x] minimize `pip install jupyter` : simple `pip install ipython` is not enough; figure out what it needs. -- gh-30
- [x] pip caching on CI -- tracked at gh-33, done in gh-37
- [x] numpy nodepr api
- [x] figure a usable meson version (not master) --- 0.60.3 seems OK, but gh-45 
- [x] do we still need requirements.txt? -- yes, lib build does not install user dependencies
- [x]  document the process
- [ ] what is the Cython error mode / document how to troubleshoot
- [ ] С++ compile switches (-O3 -fopenmp etc)

**Comment by ev-br** [comment]
pip deprecations seems fine:

```
$ git clean -xdf
$ pip install . --use-feature=in-tree-build
$ pytest --pyargs mc_lib -v
```
passes. Examples build and run fine. This is with
```
$ pip --version
pip 21.2.1
```

So, ticking this box, this pip change seems harmless.

**Comment by ev-br** [comment]
An attempt at a pip editable install fails immediately with a sane error:

```
$ pip install -e .
ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: /home/br/sweethome/proj/mc_lib
(A "pyproject.toml" file was found, but editable mode currently requires a setuptools-based build.)
```

**Comment by ev-br** [comment]
CI pip cache is up and running, cf gh-33

**Comment by ev-br** [comment]
Ok, not much to do here anymore, closing
